apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
  labels:
    app: mixcr
spec:
  replicas: 200
  selector:
    matchLabels:
      app: mixcr
  template:
    metadata:
      labels:
        app: mixcr
    spec:
      containers:
      - name: mixcr_twopods
        image: <your_docker_image>
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "16000m"
