apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: final
  region: us-east-1
nodeGroups:
  - name: ng-spot
    labels:
      lifecycle: Ec2Spot
    taints:
      spotInstance: true:PreferNoSchedule
    minSize: 50
    maxSize: 100
    desiredCapacity: 100
    volumeSize: 150
    volumeType: gp2
    instancesDistribution: # At least two instance types should be specified
      instanceTypes:
        - c5.9xlarge
        - c5d.9xlarge
        - c5n.9xlarge
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0 # all the instances will be spot instances
      spotInstancePools: 3
      SpotAllocationStrategy: lowes-price
